/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormMenu;

/**
 *
 * @author WINDOWS 10
 */
public class Laporan extends javax.swing.JPanel {

    /**
     * Creates new form Laporan
     */
    public Laporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        BackgroundLaporan = new javax.swing.JLabel();
        BackgorundLaporantotal = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(280, 64));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 1500, 650));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laporan Total", "Laporan Penjualan", "Laporan Pembelian", " " }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 370, 50));

        BackgroundLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/TampilanLaporan.png"))); // NOI18N
        add(BackgroundLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BackgorundLaporantotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/TampilanDashboard.png"))); // NOI18N
        BackgorundLaporantotal.setText("jLabel1");
        add(BackgorundLaporantotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgorundLaporantotal;
    private javax.swing.JLabel BackgroundLaporan;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
