/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormMenu;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author WINDOWS 10
 */
public class Produkmasuk extends javax.swing.JPanel {

    /**
     * Creates new form Produkmasuk
     */
    private void load_tabelsupplierpm() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("ID Supplier");
        model.addColumn("Nama Supplier");
        model.addColumn("Alamat");
        model.addColumn("No. Telepon");
        model.addColumn("Keterangan");
        
        try { 
            int no = 1;
            String sql = "SELECT * FROM supplier ORDER BY id_supplier";
            Connection conn = (Connection) koneksi.configDB();
            Statement stm = conn.createStatement();
            ResultSet res = stm.executeQuery(sql);
            while (res.next()){
                model.addRow (new Object[] {no++, res.getString(1),
                    res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
            }
        TabelPertama.setModel(model);
        } catch (SQLException e){
        }
    }
    
     private void load_tabelbarangpm() {
        DefaultTableModel model2 = new DefaultTableModel();
        model2.addColumn("No");
        model2.addColumn("ID Alat Musik");
        model2.addColumn("Nama Alat Musik");
        model2.addColumn("Harga");
        model2.addColumn("Stok");
        
        try { 
            int no = 1;
            String sql = "SELECT idalatmusik, namaalatmusik, harga_jual, stok FROM alatmusik ORDER BY idalatmusik";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()){
                model2.addRow (new Object[] {no++, res.getString(1),
                    res.getString(2), res.getString(3), res.getString(4)});
            }
        TabelPertama.setModel(model2);
        } catch (SQLException e){
        }
    }
  
    public Produkmasuk() {
        initComponents();
        load_tabelbarangpm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtKembalian = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelPertama = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtPencarian = new javax.swing.JTextField();
        txtSupplier = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtHargaBeli = new javax.swing.JTextField();
        txtTotalHarga = new javax.swing.JTextField();
        txtBayar = new javax.swing.JTextField();
        opsiTabel = new javax.swing.JComboBox<>();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtKembalian.setBorder(null);
        txtKembalian.setOpaque(false);
        add(txtKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 799, 470, 40));

        TabelPertama.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelPertama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelPertamaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelPertama);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 800, 290));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 552, 970, 400));

        txtPencarian.setBorder(null);
        txtPencarian.setOpaque(false);
        add(txtPencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 137, 230, 30));

        txtSupplier.setBorder(null);
        txtSupplier.setOpaque(false);
        add(txtSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 240, 410, 30));

        txtJumlah.setBorder(null);
        txtJumlah.setOpaque(false);
        add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 350, 240, 30));

        txtHargaBeli.setBorder(null);
        txtHargaBeli.setOpaque(false);
        add(txtHargaBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 350, 240, 30));

        txtTotalHarga.setBorder(null);
        txtTotalHarga.setOpaque(false);
        add(txtTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 570, 470, 40));

        txtBayar.setBorder(null);
        txtBayar.setOpaque(false);
        add(txtBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 684, 470, 40));

        opsiTabel.setBackground(new java.awt.Color(255, 255, 255));
        opsiTabel.setEditable(true);
        opsiTabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        opsiTabel.setForeground(new java.awt.Color(0, 0, 0));
        opsiTabel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BARANG", "SUPPLIER", " " }));
        opsiTabel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opsiTabelItemStateChanged(evt);
            }
        });
        add(opsiTabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 200, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/TampilanProdukmasuk.png"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void opsiTabelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opsiTabelItemStateChanged
        if(opsiTabel.getSelectedIndex() == 0){
            load_tabelbarangpm();
            
        }else{
            load_tabelsupplierpm();
        }
    }//GEN-LAST:event_opsiTabelItemStateChanged

    public int xpengalihan;
    private void TabelPertamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelPertamaMouseClicked
        int x = TabelPertama.getSelectedRow();
        
        String id = TabelPertama.getValueAt(x, 1).toString();
        String nama = TabelPertama.getValueAt(x, 2).toString();
        String harga = TabelPertama.getValueAt(x,3).toString();
    }//GEN-LAST:event_TabelPertamaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelPertama;
    private javax.swing.JLabel background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> opsiTabel;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtHargaBeli;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtPencarian;
    private javax.swing.JTextField txtSupplier;
    private javax.swing.JTextField txtTotalHarga;
    // End of variables declaration//GEN-END:variables
}
