/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormMenu;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author WINDOWS 10
 */
public class Produkmasuk extends javax.swing.JPanel {

    /**
     * Creates new form Produkmasuk
     */
    private void load_tabelsupplierpm() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("ID Supplier");
        model.addColumn("Nama Supplier");
        model.addColumn("Alamat");
        model.addColumn("No. Telepon");
        model.addColumn("Keterangan");
        
        try { 
            int no = 1;
            String sql = "SELECT * FROM supplier ORDER BY id_supplier";
            Connection conn = (Connection) koneksi.configDB();
            Statement stm = conn.createStatement();
            ResultSet res = stm.executeQuery(sql);
            while (res.next()){
                model.addRow (new Object[] {no++, res.getString(1),
                    res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
            }
        TabelPertama.setModel(model);
        } catch (SQLException e){
        }
    }
    
     private void load_tabelbarangpm() {
        DefaultTableModel model2 = new DefaultTableModel();
        model2.addColumn("No");
        model2.addColumn("ID Alat Musik");
        model2.addColumn("Nama Alat Musik");
        model2.addColumn("Harga");
        model2.addColumn("Stok");
        
        try { 
            int no = 1;
            String sql = "SELECT idalatmusik, namaalatmusik, harga_jual, stok FROM alatmusik ORDER BY idalatmusik";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()){
                model2.addRow (new Object[] {no++, res.getString(1),
                    res.getString(2), res.getString(3), res.getString(4)});
            }
        TabelPertama.setModel(model2);
        } catch (SQLException e){
        }
    }
  
    public Produkmasuk() {
        initComponents();
        load_tabelbarangpm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPencarian = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelPertama = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtPencarian1 = new javax.swing.JTextField();
        txtPencarian2 = new javax.swing.JTextField();
        txtPencarian3 = new javax.swing.JTextField();
        txtPencarian4 = new javax.swing.JTextField();
        txtPencarian5 = new javax.swing.JTextField();
        txtPencarian6 = new javax.swing.JTextField();
        opsiTabel = new javax.swing.JComboBox<>();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPencarian.setBorder(null);
        txtPencarian.setOpaque(false);
        txtPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPencarianActionPerformed(evt);
            }
        });
        add(txtPencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 799, 470, 40));

        TabelPertama.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelPertama);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 800, 290));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 552, 970, 400));

        txtPencarian1.setBorder(null);
        txtPencarian1.setOpaque(false);
        txtPencarian1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPencarian1ActionPerformed(evt);
            }
        });
        add(txtPencarian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 137, 230, 30));

        txtPencarian2.setBorder(null);
        txtPencarian2.setOpaque(false);
        txtPencarian2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPencarian2ActionPerformed(evt);
            }
        });
        add(txtPencarian2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 240, 410, 30));

        txtPencarian3.setBorder(null);
        txtPencarian3.setOpaque(false);
        txtPencarian3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPencarian3ActionPerformed(evt);
            }
        });
        add(txtPencarian3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 350, 240, 30));

        txtPencarian4.setBorder(null);
        txtPencarian4.setOpaque(false);
        txtPencarian4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPencarian4ActionPerformed(evt);
            }
        });
        add(txtPencarian4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 350, 240, 30));

        txtPencarian5.setBorder(null);
        txtPencarian5.setOpaque(false);
        txtPencarian5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPencarian5ActionPerformed(evt);
            }
        });
        add(txtPencarian5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 570, 470, 40));

        txtPencarian6.setBorder(null);
        txtPencarian6.setOpaque(false);
        txtPencarian6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPencarian6ActionPerformed(evt);
            }
        });
        add(txtPencarian6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 684, 470, 40));

        opsiTabel.setBackground(new java.awt.Color(255, 255, 255));
        opsiTabel.setEditable(true);
        opsiTabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        opsiTabel.setForeground(new java.awt.Color(0, 0, 0));
        opsiTabel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BARANG", "SUPPLIER", " " }));
        opsiTabel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opsiTabelItemStateChanged(evt);
            }
        });
        add(opsiTabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 200, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/TampilanProdukmasuk.png"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPencarianActionPerformed

    private void txtPencarian1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPencarian1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPencarian1ActionPerformed

    private void txtPencarian2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPencarian2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPencarian2ActionPerformed

    private void txtPencarian3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPencarian3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPencarian3ActionPerformed

    private void txtPencarian4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPencarian4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPencarian4ActionPerformed

    private void txtPencarian5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPencarian5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPencarian5ActionPerformed

    private void txtPencarian6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPencarian6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPencarian6ActionPerformed

    private void opsiTabelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opsiTabelItemStateChanged
        if(opsiTabel.getSelectedIndex() == 0){
            load_tabelbarangpm();
        }else{
            load_tabelsupplierpm();
        }
    }//GEN-LAST:event_opsiTabelItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelPertama;
    private javax.swing.JLabel background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> opsiTabel;
    private javax.swing.JTextField txtPencarian;
    private javax.swing.JTextField txtPencarian1;
    private javax.swing.JTextField txtPencarian2;
    private javax.swing.JTextField txtPencarian3;
    private javax.swing.JTextField txtPencarian4;
    private javax.swing.JTextField txtPencarian5;
    private javax.swing.JTextField txtPencarian6;
    // End of variables declaration//GEN-END:variables
}
