/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package FormMenu;

/**
 *
 * @author WINDOWS 10
 */
public class TubuhUtama extends javax.swing.JFrame {

    
    Dashboard dashboard = new Dashboard();
    Barang barang = new Barang();
    Transaksi transaksi = new Transaksi();
    Produkmasuk produkmasuk = new Produkmasuk();
    Supplier supplier = new Supplier();
    Laporan laporan = new Laporan();
    Pengaturan pengaturan = new Pengaturan(); 
    
    public boolean menu1 = true;
    public boolean menu2 = true;
    public boolean menu3 = true;
    public boolean menu4 = true;
    
    

    
    private void hubungan(){
        jPanel1.add(dashboard);
        jPanel1.add(barang);
        jPanel1.add(transaksi);
        jPanel1.add(produkmasuk);
        jPanel1.add(supplier);
        jPanel1.add(laporan);
        jPanel1.add(pengaturan);
        
        dashboard.setVisible(true);
        barang.setVisible(false);
        transaksi.setVisible(false);
        produkmasuk.setVisible(false);
        supplier.setVisible(false);
        laporan.setVisible(false);
        pengaturan.setVisible(false);
    }
    
    private void opsiMenu(){
        dashboard.setVisible(false);
        barang.setVisible(false);
        produkmasuk.setVisible(false);
        transaksi.setVisible(false);
        supplier.setVisible(false);
        laporan.setVisible(false);
        pengaturan.setVisible(false);
    }
    private void menuColor(){
        MenuDashboard.setBackground(new java.awt.Color(244, 239, 224));
        txtDashboard.setForeground(new java.awt.Color(153,153,153));
        MenuBarang.setBackground(new java.awt.Color(244, 239, 224));
        txtBarang.setForeground(new java.awt.Color(153,153,153));
        MenuProdukmasuk.setBackground(new java.awt.Color(244, 239, 224));
        txtProdukmasuk.setForeground(new java.awt.Color(153,153,153));
        MenuTransaksi.setBackground(new java.awt.Color(244, 239, 224));
        txtTransaksi.setForeground(new java.awt.Color(153,153,153));
        MenuSupplier.setBackground(new java.awt.Color(244, 239, 224));
        txtSupplier.setForeground(new java.awt.Color(153,153,153));
        MenuLaporan.setBackground(new java.awt.Color(244, 239, 224));
        txtLaporan.setForeground(new java.awt.Color(153,153,153));
        MenuPengaturan.setBackground(new java.awt.Color(244, 239, 224));
        txtPengaturan.setForeground(new java.awt.Color(153,153,153));
    }
    
    public String namauser;
    
    public TubuhUtama() {
        initComponents();
        hubungan();
        menuColor();
        MenuDashboard.setBackground(new java.awt.Color(194,184,156));
        txtDashboard.setForeground(new java.awt.Color(0,0,0));
        userinfo.setText(namauser);
        System.out.println(namauser);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        MenuDashboard = new javax.swing.JPanel();
        txtDashboard = new javax.swing.JLabel();
        MenuBarang = new javax.swing.JPanel();
        txtBarang = new javax.swing.JLabel();
        MenuProdukmasuk = new javax.swing.JPanel();
        txtProdukmasuk = new javax.swing.JLabel();
        MenuTransaksi = new javax.swing.JPanel();
        txtTransaksi = new javax.swing.JLabel();
        MenuSupplier = new javax.swing.JPanel();
        txtSupplier = new javax.swing.JLabel();
        MenuLaporan = new javax.swing.JPanel();
        txtLaporan = new javax.swing.JLabel();
        MenuPengaturan = new javax.swing.JPanel();
        txtPengaturan = new javax.swing.JLabel();
        LogoVivace = new javax.swing.JLabel();
        bacgroundsisikanan = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1010));
        getContentPane().setLayout(null);

        jPanel3.setLayout(null);

        MenuDashboard.setBackground(new java.awt.Color(244, 239, 224));
        MenuDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuDashboardMouseClicked(evt);
            }
        });
        MenuDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDashboard.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        txtDashboard.setForeground(new java.awt.Color(153, 153, 153));
        txtDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/homeicon.png"))); // NOI18N
        txtDashboard.setText("       DASHBOARD");
        MenuDashboard.add(txtDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 260, 60));

        jPanel3.add(MenuDashboard);
        MenuDashboard.setBounds(0, 300, 300, 60);

        MenuBarang.setBackground(new java.awt.Color(244, 239, 224));
        MenuBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuBarangMouseClicked(evt);
            }
        });
        MenuBarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBarang.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        txtBarang.setForeground(new java.awt.Color(153, 153, 153));
        txtBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/barangicon.png"))); // NOI18N
        txtBarang.setText("       BARANG");
        MenuBarang.add(txtBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 260, 60));

        jPanel3.add(MenuBarang);
        MenuBarang.setBounds(0, 360, 300, 60);

        MenuProdukmasuk.setBackground(new java.awt.Color(244, 239, 224));
        MenuProdukmasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuProdukmasukMouseClicked(evt);
            }
        });
        MenuProdukmasuk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtProdukmasuk.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        txtProdukmasuk.setForeground(new java.awt.Color(153, 153, 153));
        txtProdukmasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/produkmasukicon.png"))); // NOI18N
        txtProdukmasuk.setText("       PRODUK MASUK");
        MenuProdukmasuk.add(txtProdukmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 260, 60));

        jPanel3.add(MenuProdukmasuk);
        MenuProdukmasuk.setBounds(0, 420, 300, 60);

        MenuTransaksi.setBackground(new java.awt.Color(244, 239, 224));
        MenuTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuTransaksiMouseClicked(evt);
            }
        });
        MenuTransaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTransaksi.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        txtTransaksi.setForeground(new java.awt.Color(153, 153, 153));
        txtTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transaksiicon.png"))); // NOI18N
        txtTransaksi.setText("       TRANSAKSI");
        MenuTransaksi.add(txtTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 260, 60));

        jPanel3.add(MenuTransaksi);
        MenuTransaksi.setBounds(0, 480, 300, 60);

        MenuSupplier.setBackground(new java.awt.Color(244, 239, 224));
        MenuSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSupplierMouseClicked(evt);
            }
        });
        MenuSupplier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSupplier.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        txtSupplier.setForeground(new java.awt.Color(153, 153, 153));
        txtSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/suppliericon.icon.png"))); // NOI18N
        txtSupplier.setText("       SUPPLIER");
        MenuSupplier.add(txtSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 260, 60));

        jPanel3.add(MenuSupplier);
        MenuSupplier.setBounds(0, 540, 300, 60);

        MenuLaporan.setBackground(new java.awt.Color(244, 239, 224));
        MenuLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuLaporanMouseClicked(evt);
            }
        });
        MenuLaporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLaporan.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        txtLaporan.setForeground(new java.awt.Color(153, 153, 153));
        txtLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/laporanicon.png"))); // NOI18N
        txtLaporan.setText("       LAPORAN");
        MenuLaporan.add(txtLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 260, 60));

        jPanel3.add(MenuLaporan);
        MenuLaporan.setBounds(0, 600, 300, 60);

        MenuPengaturan.setBackground(new java.awt.Color(244, 239, 224));
        MenuPengaturan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPengaturanMouseClicked(evt);
            }
        });
        MenuPengaturan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPengaturan.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        txtPengaturan.setForeground(new java.awt.Color(153, 153, 153));
        txtPengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/settingicon.png"))); // NOI18N
        txtPengaturan.setText("       PENGATURAN");
        MenuPengaturan.add(txtPengaturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 260, 60));

        jPanel3.add(MenuPengaturan);
        MenuPengaturan.setBounds(0, 660, 300, 60);

        LogoVivace.setForeground(new java.awt.Color(0, 0, 0));
        LogoVivace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/VIVACEMUSIC 1.png"))); // NOI18N
        jPanel3.add(LogoVivace);
        LogoVivace.setBounds(60, 30, 170, 160);

        userinfo.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        userinfo.setForeground(new java.awt.Color(0, 0, 0));
        userinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/usericon.png"))); // NOI18N
        userinfo.setText("   Hai, Maulana");
        jPanel3.add(userinfo);
        userinfo.setBounds(40, 240, 230, 40);

        bacgroundsisikanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/BackgroundMenu.png"))); // NOI18N
        jPanel3.add(bacgroundsisikanan);
        bacgroundsisikanan.setBounds(0, 0, 320, 1010);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 320, 1010);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 1010));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(320, 0, 1600, 1010);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDashboardMouseClicked
        opsiMenu();
        dashboard.setVisible(true);
        menuColor();
        MenuDashboard.setBackground(new java.awt.Color(194,184,156));
        txtDashboard.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_MenuDashboardMouseClicked

    private void MenuProdukmasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuProdukmasukMouseClicked
        opsiMenu();
        produkmasuk.setVisible(menu2);
        menuColor();
        MenuProdukmasuk.setBackground(new java.awt.Color(194,184,156));
        txtProdukmasuk.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_MenuProdukmasukMouseClicked

    private void MenuBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuBarangMouseClicked
        opsiMenu();
        barang.setVisible(menu1);
        menuColor();
        MenuBarang.setBackground(new java.awt.Color(194,184,156));
        txtBarang.setForeground(new java.awt.Color(0,0,0));
        barang.kosongkan();
    }//GEN-LAST:event_MenuBarangMouseClicked

    private void MenuSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSupplierMouseClicked
        opsiMenu();
        supplier.setVisible(menu3);
        menuColor();
        MenuSupplier.setBackground(new java.awt.Color(194,184,156));
        txtSupplier.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_MenuSupplierMouseClicked

    private void MenuTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuTransaksiMouseClicked
        opsiMenu();
        transaksi.setVisible(true);
        menuColor();
        MenuTransaksi.setBackground(new java.awt.Color(194,184,156));
        txtTransaksi.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_MenuTransaksiMouseClicked

    private void MenuLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLaporanMouseClicked
        opsiMenu();
        laporan.setVisible(true);
        menuColor();
        MenuLaporan.setBackground(new java.awt.Color(194,184,156));
        txtLaporan.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_MenuLaporanMouseClicked

    private void MenuPengaturanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPengaturanMouseClicked
        opsiMenu();
        pengaturan.setVisible(menu4);
        menuColor();
        MenuPengaturan.setBackground(new java.awt.Color(194,184,156));
        txtPengaturan.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_MenuPengaturanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TubuhUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TubuhUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TubuhUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TubuhUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TubuhUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoVivace;
    private javax.swing.JPanel MenuBarang;
    private javax.swing.JPanel MenuDashboard;
    private javax.swing.JPanel MenuLaporan;
    private javax.swing.JPanel MenuPengaturan;
    private javax.swing.JPanel MenuProdukmasuk;
    private javax.swing.JPanel MenuSupplier;
    private javax.swing.JPanel MenuTransaksi;
    private javax.swing.JLabel bacgroundsisikanan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtBarang;
    private javax.swing.JLabel txtDashboard;
    private javax.swing.JLabel txtLaporan;
    private javax.swing.JLabel txtPengaturan;
    private javax.swing.JLabel txtProdukmasuk;
    private javax.swing.JLabel txtSupplier;
    private javax.swing.JLabel txtTransaksi;
    public static final javax.swing.JLabel userinfo = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables

}
